# PlateBridge Pod Configuration
# Copy this file to config.yaml and fill in your values

# Portal connection
portal_url: "https://your-portal.vercel.app"
pod_api_key: "pbk_your_api_key_here"  # Get from portal /pods page

# Pod identification
pod_id: "main-gate-pod"  # Unique name for this pod
camera_id: "your-camera-uuid"  # Get from portal /cameras page
camera_name: "Main Gate Camera"
site_id: "your-site-uuid"  # Get from portal /properties page
site_name: "main-gate"
company_id: "your-company-uuid"  # Get from portal /companies page

# Camera settings
camera_rtsp_url: "rtsp://192.168.1.100:554/stream"  # Your camera's RTSP URL
min_confidence: 0.75  # Minimum confidence for plate detection (0.0-1.0)

# Streaming configuration
enable_streaming: true  # Enable live stream server
stream_port: 8000  # Port for stream server
stream_secret: "change-this-secret"  # Shared secret with portal (set POD_STREAM_SECRET in Vercel)
public_ip: "auto"  # Public IP or "auto" to detect

# Recording configuration
record_on_detection: true  # Auto-record when plate detected
recordings_dir: "/tmp/recordings"  # Where to save clips temporarily
recording_duration: 30  # Seconds to record per clip

# MQTT configuration (for Frigate integration)
enable_mqtt: true
mqtt_host: "localhost"
mqtt_port: 1883
mqtt_topic: "frigate/events"
# mqtt_username: "optional"
# mqtt_password: "optional"

# Refresh intervals
whitelist_refresh_interval: 300  # Seconds (5 minutes)
heartbeat_interval: 60  # Seconds (1 minute)
