# PlateBridge Pod Configuration
# Copy this file to config.yaml and fill in your values
# Agent location: /homes/jstein/platebridgeofficial/pod-agent/complete_pod_agent.py

# Portal connection
portal_url: "https://your-portal.vercel.app"
pod_api_key: "pbk_your_api_key_here"  # Get from portal /pods page

# Pod identification
pod_id: "main-gate-pod"  # Unique name for this pod (auto-registers)
camera_id: "gate-camera-1"  # Unique ID for this camera (auto-registers)
camera_name: "Main Gate Camera"  # Human-readable name
camera_position: "main entrance"  # Optional: where camera is located

# Camera settings
camera_rtsp_url: "rtsp://192.168.1.100:554/stream"  # Your camera's RTSP URL
min_confidence: 0.75  # Minimum confidence for plate detection (0.0-1.0)

# Streaming configuration
enable_streaming: true  # Enable live stream server
stream_port: 8000  # Port for stream server
stream_secret: "change-this-secret"  # Shared secret with portal (set POD_STREAM_SECRET in Vercel)
public_ip: "auto"  # Public IP or "auto" to detect

# Recording configuration
record_on_detection: true  # Auto-record when plate detected
recordings_dir: "/tmp/recordings"  # Where to save clips temporarily
recording_duration: 30  # Seconds to record per clip

# Frigate integration
enable_mqtt: true  # Enable MQTT listener for Frigate events
mqtt_host: "localhost"  # Frigate MQTT broker (usually same host)
mqtt_port: 1883
mqtt_topic: "frigate/events"  # Frigate publishes events here
# mqtt_username: "optional"
# mqtt_password: "optional"

frigate_url: "http://localhost:5000"  # Frigate API URL for snapshots
save_snapshots: true  # Download snapshots from Frigate for each detection

# Refresh intervals
whitelist_refresh_interval: 300  # Seconds (5 minutes)
heartbeat_interval: 60  # Seconds (1 minute)
